---
- name: Install GPG key
  command: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

- name: Configure apt repository
  template: src="docker.list.j2" dest="/etc/apt/sources.list.d/docker.list"

- name: Update respository information
  command: apt-get update

- name: Install docker engine
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: docker-engine
    state: latest
