---
- name: Download Kubernetes binaries
  get_url:
    url: "{{ kube_download_url_base }}{{ item }}"
    dest: "{{ bin_dir }}/{{ item }}"
    mode: 0755
    validate_certs: False
  environment:
    http_proxy: "{{ http_proxy|default('') }}"
    https_proxy: "{{ https_proxy|default('') }}"
    no_proxy: "{{ no_proxy|default('') }}"
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-proxy
    - kube-scheduler
    - kubectl
    - kubelet
