---
- name: Install flannel
  action: "{{ ansible_pkg_mgr }}"
  args:
        name: flannel
        state: latest
  when: not is_atomic and not is_coreos

- name: Install from github
  include: github-release.yml
  when: is_coreos

- name: Install Flannel config file
  template: src=flanneld.j2 dest=/etc/sysconfig/flanneld
  notify:
    - restart flannel
