---
- name: Open firewalld port for the kubelet
  firewalld: port=10250/tcp permanent=false state=enabled

- name: Save firewalld port for the kubelet
  firewalld: port=10250/tcp permanent=true state=enabled

