---
- name: restart flannel
  service: name=flanneld state=restarted
  notify:
    - stop docker
    - delete docker0
    - start docker

- name: stop docker
  service: name=docker state=stopped
  when: '"docker0" in ansible_interfaces'

- name: delete docker0
  command: ip link delete docker0
  when: '"docker0" in ansible_interfaces'

- name: start docker
  service: name=docker state=started
  # NB: even if docker0 is deleted above, ansible_interfaces is not affected
  # since it is set once at the beginning of the role
  when: '"docker0" in ansible_interfaces'
